window.theme_brz_dark = {
                            indx:
                            {
                                "bg-color": "#2a2e32",
                                "fg-color": "#d4d4d4",

                                "input-bg-color": "#254455",
                                "input-fg-color": "#0da9f5",

                                "grey-40": "#585b5e40",
                                "grey-99": "#585b5e99",
                                "--grey-ff": "#585b5eff",
                            },
                            chungus:
                            {
                                "bg-color": "#2a2e32",
                                "fg-color": "#d4d4d4",
                                "hard-outline-color": "#64686b",
                                "asset-acsent-color": "#64686b",
                                "dark-blue-hl": "#1f485e",
                                "light-blue-hl": "#3daee9",
                                "transparent-blue": "#3daee938",
                                "denyal-red": "#da4453",
                                "blue-outline": "#587180",

                                "icon-filter": "brightness(1000) brightness(83%)",
                                "icon-hover": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(67%)",
                                "icon-active": "brightness(1000)",

                                "action-btn-1": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%)",
                                "action-btn-2": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(1.4)",
                                "action-btn-3": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(2)",

                                "action-btn-active-1": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(140%)",
                                "action-btn-active-2": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(1.4) brightness(140%)",
                                "action-btn-active-3": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(2) brightness(160%)",

                                "grey-40": "#585b5e40",
                                "grey-50": "#585b5e50",
                                "grey-80": "#585b5e80",
                                "grey-90": "#585b5e90",
                                "grey-99": "#585b5e99",
                                "grey-ff": "#585b5eff",

                                "grey-solid": "#585b5e",
                                "link-blue": "#0da9f5",
                                "link-purple": "#a0a",
                                "link-active-red": "#f00",
                                "bg-blue-dark": "#254455",

                                "code-bg": "#494c50",

                                "copy-border": "#585b5e",
                                "copy-bg": "#3c3f42",
                                "copy-fg": "#d4d4d4",
                                "copy-border-hover": "#d4d4d480",
                                "copy-bg-hover": "#d4d4d430",
                                "copy-border-active": "#d4d4d499",
                                "copy-bg-active": "#d4d4d440",
                                "copy-success-bd": "#00ff9999",
                                "copy-success-bg": "#00ff9919",
                                "copy-success-fg": "#00ff9999",

                                "context-hover-border": "#66b8e3",
                                "context-hover-bg": "#1f485e40",
                                "context-hover-fg": "#9dc6cd",
                                "context-active-bg": "#1f485eab",

                                "table-header-bg": "#585b5e90",
                                "table-row-alt-bg": "#585b5e40",
                                "table-header-fg": "#fff",
                            },
                            settings:
                            {
                                "bg-color": "#2a2e32",
                                "fg-color": "#d4d4d4",
                                "menu-hover": "#1f485e",
                            },
                            appearance:
                            {
                                "fg-color": "#d4d4d4",
                                "man-color": "#000a",

                                "card-1-filt": "brightness(1)",
                                "card-2-filt": "brightness(1.25)",
                                "card-3-filt": "brightness(2)",

                                "light-blue-hl": "#3daee9",
                            },
                            morethemes:
                            {
                                "bg-color": "#2a2e32",
                                "fg-color": "#d4d4d4",
                                "man-color": "#000a",

                                "card-1": "brightness(1)",
                                "card-2": "brightness(1.75)",
                                "card-3": "brightness(2)",

                                "icon-1": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%)",
                                "icon-2": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(1.4)",
                                "icon-3": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(2)",
                            },
                            customthemes:
                            {
                                "bg-color": "#2a2e32",
                                "fg-color": "#d4d4d4",

                                "icon-1": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%)",
                                "icon-2": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(1.4)",
                                "icon-3": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(2)",
                            },
                            prism: {
                                "prism-block-bg": "#31353990",
                                "prism-inline-bg": "#31353990",
                                "prism-text-color": "#ccc",
                                "prism-comment": "#999",
                                "prism-block-comment": "#999",
                                "prism-prolog": "#999",
                                "prism-doctype": "#999",
                                "prism-cdata": "#999",
                                "prism-punctuation": "#ccc",
                                "prism-tag": "#e2777a",
                                "prism-attr-name": "#ffb86c",
                                "prism-attr-value": "#7ec699",
                                "prism-operator": "#67cdcc",
                                "prism-entity": "#67cdcc",
                                "prism-url": "#67cdcc",
                                "prism-property": "#67cdcc",
                                "prism-symbol": "#f8c555",
                                "prism-string": "#7ec699",
                                "prism-char": "#7ec699",
                                "prism-regex": "#7ec699",
                                "prism-number": "#f08d49",
                                "prism-constant": "#f8c555",
                                "prism-variable": "#6196cc",
                                "prism-class-name": "#ffd700",
                                "prism-function": "#f08d49",
                                "prism-function-name": "#6196cc",
                                "prism-keyword": "#cc99cd",
                                "prism-selector": "#cc99cd",
                                "prism-builtin": "#cc99cd",
                                "prism-important": "#cc99cd",
                                "prism-atrule": "#cc99cd",
                                "prism-deleted": "#e2777a",
                                "prism-inserted": "#00d000",
                                "prism-comment-font-style": "oblique",
                                "prism-comment-font-weight": "400",
                                "prism-block-comment-font-style": "oblique",
                                "prism-block-comment-font-weight": "400",
                                "prism-prolog-font-style": "oblique",
                                "prism-prolog-font-weight": "400",
                                "prism-doctype-font-style": "oblique",
                                "prism-doctype-font-weight": "400",
                                "prism-cdata-font-style": "oblique",
                                "prism-cdata-font-weight": "400",
                                "prism-punctuation-font-style": "normal",
                                "prism-punctuation-font-weight": "400",
                                "prism-tag-font-style": "normal",
                                "prism-tag-font-weight": "400",
                                "prism-attr-name-font-style": "normal",
                                "prism-attr-name-font-weight": "400",
                                "prism-attr-value-font-style": "normal",
                                "prism-attr-value-font-weight": "400",
                                "prism-deleted-font-style": "normal",
                                "prism-deleted-font-weight": "400",
                                "prism-entity-font-style": "normal",
                                "prism-entity-font-weight": "400",
                                "prism-operator-font-style": "normal",
                                "prism-operator-font-weight": "400",
                                "prism-url-font-style": "normal",
                                "prism-url-font-weight": "400",
                                "prism-property-font-style": "normal",
                                "prism-property-font-weight": "400",
                                "prism-symbol-font-style": "normal",
                                "prism-symbol-font-weight": "400",
                                "prism-char-font-style": "normal",
                                "prism-char-font-weight": "400",
                                "prism-regex-font-style": "normal",
                                "prism-regex-font-weight": "400",
                                "prism-string-font-style": "italic",
                                "prism-string-font-weight": "400",
                                "prism-number-font-style": "normal",
                                "prism-number-font-weight": "400",
                                "prism-constant-font-style": "normal",
                                "prism-constant-font-weight": "400",
                                "prism-variable-font-style": "normal",
                                "prism-variable-font-weight": "400",
                                "prism-class-name-font-style": "normal",
                                "prism-class-name-font-weight": "400",
                                "prism-function-font-style": "normal",
                                "prism-function-font-weight": "400",
                                "prism-function-name-font-style": "normal",
                                "prism-function-name-font-weight": "400",
                                "prism-keyword-font-style": "normal",
                                "prism-keyword-font-weight": "400",
                                "prism-selector-font-style": "normal",
                                "prism-selector-font-weight": "400",
                                "prism-builtin-font-style": "normal",
                                "prism-builtin-font-weight": "400",
                                "prism-important-font-style": "normal",
                                "prism-important-font-weight": "700",
                                "prism-atrule-font-style": "normal",
                                "prism-atrule-font-weight": "400",
                                "prism-inserted-font-style": "normal",
                                "prism-inserted-font-weight": "400",
                                "prism-bold-font-style": "normal",
                                "prism-bold-font-weight": "700",
                                "prism-italic-font-style": "italic",
                                "prism-italic-font-weight": "400"
                            },

                            gitgraph:
                            {
                                "versioning-graph-bg": "#2a2e32",
                                "versioning-graph-right-border": "#585b5e40",

                                "versioning-graph-0": "#0dc5c5",
                                "versioning-graph-1": "#107df0",
                                "versioning-graph-2": "#7f0fbb",
                                "versioning-graph-3": "#a417e0",
                                "versioning-graph-4": "#e01490",
                                "versioning-graph-5": "#ed1414",
                                "versioning-graph-6": "#f04b10",
                                "versioning-graph-7": "#f68010",
                                "versioning-graph-8": "#f6b010",
                                "versioning-graph-9": "#6bd00b",
                                "versioning-graph-a": "#10d016",
                                "versioning-graph-b": "#1abc9c",
                            },
                            morefonts:
                            {
                                "bg-color": "#2a2e32",
                                "fg-color": "#d4d4d4",

                                "hl-blue-1": "#3daee9",
                                "hl-blue-2": "#3daee922",
                                "hl-blue-3": "#2eb7ff",
                                "hl-blue-4": "#2eb7ff40",

                                "icon-1": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%)",
                                "icon-2": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(1.4)",
                                "icon-3": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(2)",
                            },
                            models:
                            {
                                "bg-color": "#2a2e32",
                                "fg-color": "#d4d4d4",
                                "table-waght": "#35383c",

                                "hl-blue-1": "#3daee9",
                                "hl-blue-2": "#2f4e60",

                                "row-filter": "brightness(0) invert(83%)",
                                "filt-hover": "#fff1",
                                "filt-raw": "#fff3",

                                "rm-action-defult": "brightness(0) invert(83%)",
                                "rm-action-hover": "brightness(0) saturate(100%) invert(14%) sepia(83%) saturate(2200%) hue-rotate(330deg) brightness(150%) contrast(124%)",
                                "rm-action-active": "brightness(0) saturate(100%) invert(14%) sepia(83%) saturate(2200%) hue-rotate(330deg) brightness(200%) contrast(124%)",

                                "mv-defult": "brightness(0) invert(83%)",
                                "mv-filter": "invert(62%) sepia(92%) saturate(1934%) hue-rotate(171deg) brightness(99%) contrast(84%)",

                                "act-defult": "brightness(0) invert(83%)",
                                "act-active": "invert(60%) sepia(70%) saturate(358%) hue-rotate(97deg) brightness(94%) contrast(88%)",
                            },
                            master:
                            {
                                "bg-color": "#232629",
                                "fg-color": "#d4d4d4",
                                "topper-color": "#2a2e32",
                                "hard-outline-color": "#64686b",
                                "tab-inactive": "#23262a",
                                "dark-blue-hl": "#1f485e",
                                "lighter-blue-hl": "#3daee9",
                                "blue-outline": "#587180",
                                "tab-inactive-blue": "#296a8c",

                                "tab-close-1": "brightness(0) saturate(100%) invert(56.9%) saturate(2.8%) hue-rotate(210deg)",
                                "tab-close-2": "brightness(1) saturate(75%) hue-rotate(340deg) brightness(100%)",
                                "tab-close-3": "brightness(1) saturate(100%) hue-rotate(340deg) brightness(100%)",

                                "action-btn-1": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%)",
                                "action-btn-2": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(1.4)",
                                "action-btn-3": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(2)",
                            },
                        };
