window.theme_cnt_light = {
                            indx: {
                                "bg-color": "#ffffff",
                                "fg-color": "#000000",

                                "input-bg-color": "#f9f9f9",
                                "input-fg-color": "#0057d8",

                                "grey-40": "#585b5e40",
                                "grey-99": "#585b5e99",
                                "grey-ff": "#585b5eff",
                            },
                            chungus: {
                                "bg-color": "#ffffff",
                                "fg-color": "#000000",
                                "hard-outline-color": "#333333",
                                "asset-accent-color": "#2980b9",
                                "dark-blue-hl": "#004c97",
                                "light-blue-hl": "#007bff",
                                "transparent-blue": "#007bff38",
                                "denial-red": "#da4453",
                                "blue-outline": "#0068c0",

                                "icon-filter": "brightness(1000) saturate(6%) hue-rotate(206deg) brightness(25%)",
                                "icon-hover": "brightness(1000) saturate(6%) hue-rotate(206deg) brightness(45%)",
                                "icon-active": "brightness(1000)",

                                "action-btn-1": "brightness(1000) saturate(5%) hue-rotate(206deg) brightness(50%)",
                                "action-btn-2": "brightness(1000) saturate(5%) hue-rotate(206deg) brightness(35%)",
                                "action-btn-3": "brightness(1000) saturate(5%) hue-rotate(206deg) brightness(25%)",

                                "action-btn-active-1": "brightness(1000) saturate(5%) hue-rotate(206deg) brightness(50%) brightness(85%)",
                                "action-btn-active-2": "brightness(1000) saturate(5%) hue-rotate(206deg) brightness(35%) brightness(70%)",
                                "action-btn-active-3": "brightness(1000) saturate(5%) hue-rotate(206deg) brightness(25%) brightness(60%)",

                                "grey-40": "#66666640",
                                "grey-50": "#66666650",
                                "grey-80": "#66666680",
                                "grey-90": "#66666690",
                                "grey-99": "#66666699",
                                "grey-ff": "#666666ff",

                                "grey-solid": "#666666",
                                "link-blue": "#0057d8",
                                "link-purple": "#6a00a8",
                                "link-active-red": "#cc0000",
                                "bg-blue-dark": "#eaf3ff",

                                "code-bg": "#f4f4f4",

                                "copy-border": "#000000",
                                "copy-bg": "#00000011",
                                "copy-fg": "#000000",
                                "copy-border-hover": "#000000",
                                "copy-bg-hover": "#00000022",
                                "copy-border-active": "#000000",
                                "copy-bg-active": "#00000033",
                                "copy-success-bd": "#00a00099",
                                "copy-success-bg": "#00a00019",
                                "copy-success-fg": "#00a00099",

                                "context-hover-border": "#007bff",
                                "context-hover-bg": "#007bff20",
                                "context-hover-fg": "#002a60",
                                "context-active-bg": "#007bff60",

                                "table-container-bg": "#ffffff",
                                "table-header-bg": "#dcdcdc",
                                "table-row-odd-bg": "#f3f3f3",
                                "table-row-even-bg": "#ffffff",
                                "table-header-fg": "#000000"
                            },
                            prism: {
                                "prism-block-bg": "#f0f0f0",
                                "prism-inline-bg": "#f0f0f0",
                                "prism-text-color": "#000",
                                "prism-comment": "#555",
                                "prism-block-comment": "#555",
                                "prism-prolog": "#555",
                                "prism-doctype": "#555",
                                "prism-cdata": "#555",
                                "prism-punctuation": "#000",
                                "prism-tag": "#0057d8",
                                "prism-attr-name": "#0a3d91",
                                "prism-attr-value": "#006a00",
                                "prism-operator": "#007bff",
                                "prism-entity": "#007bff",
                                "prism-url": "#007bff",
                                "prism-property": "#007bff",
                                "prism-symbol": "#b57200",
                                "prism-string": "#006a00",
                                "prism-char": "#006a00",
                                "prism-regex": "#006a00",
                                "prism-number": "#b94d00",
                                "prism-constant": "#b57200",
                                "prism-variable": "#006a00",
                                "prism-class-name": "#b57200",
                                "prism-function": "#b94d00",
                                "prism-function-name": "#007bff",
                                "prism-keyword": "#0057d8",
                                "prism-selector": "#0057d8",
                                "prism-builtin": "#0057d8",
                                "prism-important": "#a6278f",
                                "prism-atrule": "#a6278f",
                                "prism-deleted": "#c62828",
                                "prism-inserted": "#006a00",
                                "prism-comment-font-style": "oblique",
                                "prism-comment-font-weight": "400",
                                "prism-block-comment-font-style": "oblique",
                                "prism-block-comment-font-weight": "400",
                                "prism-prolog-font-style": "oblique",
                                "prism-prolog-font-weight": "400",
                                "prism-doctype-font-style": "oblique",
                                "prism-doctype-font-weight": "400",
                                "prism-cdata-font-style": "oblique",
                                "prism-cdata-font-weight": "400",
                                "prism-punctuation-font-style": "normal",
                                "prism-punctuation-font-weight": "400",
                                "prism-tag-font-style": "normal",
                                "prism-tag-font-weight": "400",
                                "prism-attr-name-font-style": "normal",
                                "prism-attr-name-font-weight": "400",
                                "prism-attr-value-font-style": "normal",
                                "prism-attr-value-font-weight": "400",
                                "prism-deleted-font-style": "normal",
                                "prism-deleted-font-weight": "400",
                                "prism-entity-font-style": "normal",
                                "prism-entity-font-weight": "400",
                                "prism-operator-font-style": "normal",
                                "prism-operator-font-weight": "400",
                                "prism-url-font-style": "normal",
                                "prism-url-font-weight": "400",
                                "prism-symbol-font-style": "normal",
                                "prism-symbol-font-weight": "400",
                                "prism-char-font-style": "normal",
                                "prism-char-font-weight": "400",
                                "prism-regex-font-style": "normal",
                                "prism-regex-font-weight": "400",
                                "prism-string-font-style": "italic",
                                "prism-string-font-weight": "400",
                                "prism-number-font-style": "normal",
                                "prism-number-font-weight": "400",
                                "prism-constant-font-style": "normal",
                                "prism-constant-font-weight": "400",
                                "prism-variable-font-style": "normal",
                                "prism-variable-font-weight": "400",
                                "prism-class-name-font-style": "normal",
                                "prism-class-name-font-weight": "400",
                                "prism-function-font-style": "normal",
                                "prism-function-font-weight": "400",
                                "prism-function-name-font-style": "normal",
                                "prism-function-name-font-weight": "400",
                                "prism-keyword-font-style": "normal",
                                "prism-keyword-font-weight": "400",
                                "prism-selector-font-style": "normal",
                                "prism-selector-font-weight": "400",
                                "prism-builtin-font-style": "normal",
                                "prism-builtin-font-weight": "400",
                                "prism-important-font-style": "normal",
                                "prism-important-font-weight": "700",
                                "prism-atrule-font-style": "normal",
                                "prism-atrule-font-weight": "400",
                                "prism-inserted-font-style": "normal",
                                "prism-inserted-font-weight": "400",
                                "prism-bold-font-style": "normal",
                                "prism-bold-font-weight": "700",
                                "prism-italic-font-style": "italic",
                                "prism-italic-font-weight": "400",
                                "prism-property-font-style": "normal",
                                "prism-property-font-weight": "400"
                            },
                            gitgraph: {
                                "versioning-graph-bg": "#ffffff",
                                "versioning-graph-right-border": "#66666640",

                                "versioning-graph-0": "#0dc5c5",
                                "versioning-graph-1": "#107df0",
                                "versioning-graph-2": "#7f0fbb",
                                "versioning-graph-3": "#a417e0",
                                "versioning-graph-4": "#e01490",
                                "versioning-graph-5": "#ed1414",
                                "versioning-graph-6": "#f04b10",
                                "versioning-graph-7": "#f68010",
                                "versioning-graph-8": "#f6b010",
                                "versioning-graph-9": "#6bd00b",
                                "versioning-graph-a": "#10d016",
                                "versioning-graph-b": "#1abc9c",
                            },
                            settings: {
                                "bg-color": "#ffffff",
                                "fg-color": "#000000",
                                "menu-hover": "#007bff33"
                            },
                            appearance: {
                                "fg-color": "#000000",
                                "man-color": "#fff8",

                                "card-1-filt": "brightness(2)",
                                "card-2-filt": "brightness(1.5)",
                                "card-3-filt": "brightness(1)",

                                "light-blue-hl": "#007bff",
                            },
                            morethemes: {
                                "bg-color": "#ffffff",
                                "fg-color": "#000000",
                                "man-color": "#fff8",

                                "card-1": "brightness(2)",
                                "card-2": "brightness(1.5)",
                                "card-3": "brightness(1)",

                                "icon-1": "brightness(1000) saturate(5%) hue-rotate(206deg) brightness(50%)",
                                "icon-2": "brightness(1000) saturate(5%) hue-rotate(206deg) brightness(35%)",
                                "icon-3": "brightness(1000) saturate(5%) hue-rotate(206deg) brightness(25%)",
                            },
                            customthemes: {
                                "bg-color": "#ffffff",
                                "fg-color": "#000000",

                                "icon-1": "brightness(1000) saturate(5%) hue-rotate(206deg) brightness(50%)",
                                "icon-2": "brightness(1000) saturate(5%) hue-rotate(206deg) brightness(35%)",
                                "icon-3": "brightness(1000) saturate(5%) hue-rotate(206deg) brightness(25%)"
                            },
                            morefonts: {
                                "bg-color": "#ffffff",
                                "fg-color": "#000000",

                                "hl-blue-1": "#3daee9",
                                "hl-blue-2": "#3daee922",
                                "hl-blue-3": "#2eb7ff",
                                "hl-blue-4": "#2eb7ff40",

                                "icon-1": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%)",
                                "icon-2": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(1.4)",
                                "icon-3": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(2)",
                            },
                            models: {
                                "bg-color": "#ffffff",
                                "fg-color": "#000000",
                                "table-waght": "#d3e0ed",

                                "hl-blue-1": "#007bff",
                                "hl-blue-2": "#bfdeff",

                                "row-filter": "brightness(0)",
                                "filt-hover": "#0003",
                                "filt-raw": "#0005",

                                "rm-action-defult": "brightness(0)",
                                "rm-action-hover": "brightness(0) saturate(100%) invert(14%) sepia(83%) saturate(2200%) hue-rotate(330deg) brightness(150%) contrast(124%)",
                                "rm-action-active": "brightness(0) saturate(100%) invert(14%) sepia(83%) saturate(2200%) hue-rotate(330deg) brightness(200%) contrast(124%)",

                                "mv-defult": "brightness(0)",
                                "mv-filter": "invert(62%) sepia(92%) saturate(1934%) hue-rotate(171deg) brightness(99%) contrast(84%)",

                                "act-defult": "brightness(0)",
                                "act-active": "invert(44%) sepia(89%) saturate(375%) hue-rotate(92deg) brightness(94%) contrast(91%)",
                                "act-active": "invert(60%) sepia(70%) saturate(358%) hue-rotate(97deg) brightness(94%) contrast(88%)",
                            },
                            master: {
                                "bg-color": "#ffffff",
                                "fg-color": "#000000",
                                "topper-color": "#ffffff",
                                "hard-outline-color": "#333333",
                                "tab-inactive": "#f1f1f1",
                                "dark-blue-hl": "#004c97",
                                "lighter-blue-hl": "#007bff",
                                "blue-outline": "#0057d8",
                                "tab-inactive-blue": "#e0ebff",

                                "tab-close-1": "brightness(0) saturate(100%) invert(10%) sepia(0%) saturate(300%) hue-rotate(0deg) brightness(100%)",
                                "tab-close-2": "brightness(1) saturate(70%) hue-rotate(340deg)",
                                "tab-close-3": "brightness(1) saturate(100%) hue-rotate(340deg) brightness(100%)",

                                "action-btn-1": "brightness(1000) saturate(5%) hue-rotate(206deg) brightness(50%)",
                                "action-btn-2": "brightness(1000) saturate(5%) hue-rotate(206deg) brightness(35%)",
                                "action-btn-3": "brightness(1000) saturate(5%) hue-rotate(206deg) brightness(25%)"
                            }
                        }
