window.theme_cnt_dark = {
                            indx: {
                                "bg-color": "#111214",
                                "fg-color": "#f0f0f0",

                                "input-bg-color": "#181a1d",
                                "input-fg-color": "#00baff",

                                "grey-40": "#5555",
                                "grey-99": "#7f8c8d99",
                                "grey-ff": "#555",
                            },
                            chungus: {
                                "bg-color": "#111214",
                                "fg-color": "#f0f0f0",
                                "hard-outline-color": "#444",
                                "asset-accent-color": "#333",
                                "dark-blue-hl": "#004e7a",
                                "light-blue-hl": "#00baff",
                                "transparent-blue": "#00baff38",
                                "denial-red": "#da4453",
                                "blue-outline": "#0070a0",

                                "icon-filter": "brightness(1000) saturate(10%) hue-rotate(200deg) brightness(80%)",
                                "icon-hover": "brightness(1000) saturate(40%) hue-rotate(190deg) brightness(110%)",
                                "icon-active": "brightness(1000)",

                                "action-btn-1": "brightness(1000) saturate(40%) hue-rotate(200deg) brightness(60%)",
                                "action-btn-2": "brightness(1000) saturate(40%) hue-rotate(200deg) brightness(90%)",
                                "action-btn-3": "brightness(1000) saturate(40%) hue-rotate(200deg) brightness(120%)",

                                "action-btn-active-1": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(140%)",
                                "action-btn-active-2": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(1.4) brightness(140%)",
                                "action-btn-active-3": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(2) brightness(160%)",

                                "grey-40": "#5555",
                                "grey-50": "#5558",
                                "grey-80": "#555c",
                                "grey-ff": "#555",

                                "grey-solid": "#555",
                                "link-blue": "#00baff",
                                "link-purple": "#c100ff",
                                "link-active-red": "#ff3b3b",
                                "bg-blue-dark": "#0d2430",

                                "code-bg": "#191a1f",

                                "copy-border": "#444",
                                "copy-bg": "#222",
                                "copy-fg": "#f0f0f0",
                                "copy-border-hover": "#00baff88",
                                "copy-bg-hover": "#00baff22",
                                "copy-border-active": "#00baffcc",
                                "copy-bg-active": "#00baff33",
                                "copy-success-bd": "#00ff99cc",
                                "copy-success-bg": "#00ff9919",
                                "copy-success-fg": "#00ff99",

                                "context-hover-border": "#00baff",
                                "context-hover-bg": "#00baff22",
                                "context-hover-fg": "#f0f0f0",
                                "context-active-bg": "#00baff55",

                                "table-header-bg": "#1e1f22",
                                "table-row-alt-bg": "#16171a",
                                "table-header-fg": "#f8f8f8",
                            },
                            prism: {
                                "prism-block-bg": "#181a1f",
                                "prism-inline-bg": "#181a1f",
                                "prism-text-color": "#f0f0f0",
                                "prism-comment": "#888",
                                "prism-block-comment": "#888",
                                "prism-prolog": "#888",
                                "prism-doctype": "#888",
                                "prism-cdata": "#888",
                                "prism-punctuation": "#ccc",
                                "prism-tag": "#ff3b3b",
                                "prism-attr-name": "#ff3b3b",
                                "prism-attr-value": "#00ffcc",
                                "prism-operator": "#00baff",
                                "prism-entity": "#00baff",
                                "prism-url": "#00baff",
                                "prism-property": "#00baff",
                                "prism-symbol": "#c100ff",
                                "prism-string": "#00ffcc",
                                "prism-char": "#00ffcc",
                                "prism-regex": "#00ffcc",
                                "prism-number": "#ff9900",
                                "prism-constant": "#ff9900",
                                "prism-variable": "#00ffcc",
                                "prism-class-name": "#ff9900",
                                "prism-function": "#00baff",
                                "prism-function-name": "#00baff",
                                "prism-keyword": "#c100ff",
                                "prism-selector": "#c100ff",
                                "prism-builtin": "#c100ff",
                                "prism-important": "#c100ff",
                                "prism-atrule": "#c100ff",
                                "prism-deleted": "#ff3b3b",
                                "prism-inserted": "#00ff99",
                                "prism-comment-font-style": "oblique",
                                "prism-comment-font-weight": "400",
                                "prism-block-comment-font-style": "oblique",
                                "prism-block-comment-font-weight": "400",
                                "prism-prolog-font-style": "oblique",
                                "prism-prolog-font-weight": "400",
                                "prism-doctype-font-style": "oblique",
                                "prism-doctype-font-weight": "400",
                                "prism-cdata-font-style": "oblique",
                                "prism-cdata-font-weight": "400",
                                "prism-punctuation-font-style": "normal",
                                "prism-punctuation-font-weight": "400",
                                "prism-tag-font-style": "normal",
                                "prism-tag-font-weight": "400",
                                "prism-attr-name-font-style": "normal",
                                "prism-attr-name-font-weight": "400",
                                "prism-attr-value-font-style": "normal",
                                "prism-attr-value-font-weight": "400",
                                "prism-deleted-font-style": "normal",
                                "prism-deleted-font-weight": "400",
                                "prism-entity-font-style": "normal",
                                "prism-entity-font-weight": "400",
                                "prism-operator-font-style": "normal",
                                "prism-operator-font-weight": "400",
                                "prism-url-font-style": "normal",
                                "prism-url-font-weight": "400",
                                "prism-symbol-font-style": "normal",
                                "prism-symbol-font-weight": "400",
                                "prism-char-font-style": "normal",
                                "prism-char-font-weight": "400",
                                "prism-regex-font-style": "normal",
                                "prism-regex-font-weight": "400",
                                "prism-string-font-style": "italic",
                                "prism-string-font-weight": "400",
                                "prism-number-font-style": "normal",
                                "prism-number-font-weight": "400",
                                "prism-constant-font-style": "normal",
                                "prism-constant-font-weight": "400",
                                "prism-variable-font-style": "normal",
                                "prism-variable-font-weight": "400",
                                "prism-class-name-font-style": "normal",
                                "prism-class-name-font-weight": "400",
                                "prism-function-font-style": "normal",
                                "prism-function-font-weight": "400",
                                "prism-function-name-font-style": "normal",
                                "prism-function-name-font-weight": "400",
                                "prism-keyword-font-style": "normal",
                                "prism-keyword-font-weight": "400",
                                "prism-selector-font-style": "normal",
                                "prism-selector-font-weight": "400",
                                "prism-builtin-font-style": "normal",
                                "prism-builtin-font-weight": "400",
                                "prism-important-font-style": "normal",
                                "prism-important-font-weight": "700",
                                "prism-atrule-font-style": "normal",
                                "prism-atrule-font-weight": "400",
                                "prism-inserted-font-style": "normal",
                                "prism-inserted-font-weight": "400",
                                "prism-bold-font-style": "normal",
                                "prism-bold-font-weight": "700",
                                "prism-italic-font-style": "italic",
                                "prism-italic-font-weight": "400",
                                "prism-property-font-style": "normal",
                                "prism-property-font-weight": "400"
                            },
                            gitgraph: {
                                "versioning-graph-bg": "#111214",
                                "versioning-graph-right-border": "#5555",

                                "versioning-graph-0": "#0dc5c5",
                                "versioning-graph-1": "#107df0",
                                "versioning-graph-2": "#7f0fbb",
                                "versioning-graph-3": "#a417e0",
                                "versioning-graph-4": "#e01490",
                                "versioning-graph-5": "#ed1414",
                                "versioning-graph-6": "#f04b10",
                                "versioning-graph-7": "#f68010",
                                "versioning-graph-8": "#f6b010",
                                "versioning-graph-9": "#6bd00b",
                                "versioning-graph-a": "#10d016",
                                "versioning-graph-b": "#1abc9c",
                            },
                            settings: {
                                "bg-color": "#111214",
                                "fg-color": "#f0f0f0",
                                "menu-hover": "#00baff33"
                            },
                            appearance: {
                                "fg-color": "#f0f0f0",
                                "man-color": "#000a",
                                "card-1-filt": "brightness(0.9)",
                                "card-2-filt": "brightness(1.4)",
                                "card-3-filt": "brightness(2)",

                                "light-blue-hl": "#00baff",
                            },
                            morethemes: {
                                "bg-color": "#111214",
                                "fg-color": "#f0f0f0",
                                "man-color": "#000a",

                                "card-1": "brightness(0.9)",
                                "card-2": "brightness(1.4)",
                                "card-3": "brightness(2)",

                                "icon-1": "brightness(1000) saturate(40%) hue-rotate(200deg) brightness(60%)",
                                "icon-2": "brightness(1000) saturate(40%) hue-rotate(200deg) brightness(90%)",
                                "icon-3": "brightness(1000) saturate(40%) hue-rotate(200deg) brightness(120%)",
                            },
                            customthemes: {
                                "bg-color": "#111214",
                                "fg-color": "#f0f0f0",

                                "icon-1": "brightness(1000) saturate(40%) hue-rotate(200deg) brightness(60%)",
                                "icon-2": "brightness(1000) saturate(40%) hue-rotate(200deg) brightness(90%)",
                                "icon-3": "brightness(1000) saturate(40%) hue-rotate(200deg) brightness(120%)",
                            },
                            morefonts: {
                                "bg-color": "#111214",
                                "fg-color": "#f0f0f0",

                                "hl-blue-1": "#3daee9",
                                "hl-blue-2": "#3daee922",
                                "hl-blue-3": "#2eb7ff",
                                "hl-blue-4": "#2eb7ff40",

                                "icon-1": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%)",
                                "icon-2": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(1.4)",
                                "icon-3": "brightness(1000) saturate(6.5%) hue-rotate(206deg) brightness(42%) brightness(2)",
                            },
                            models: {
                                "bg-color": "#0e0f10",
                                "fg-color": "#f0f0f0",
                                "table-waght": "#171c1f",

                                "hl-blue-1": "#3daee9",
                                "hl-blue-2": "#1a3746",

                                "row-filter": "brightness(0) invert(94%)",
                                "filt-hover": "#fff2",
                                "filt-raw": "#fff4",

                                "rm-action-defult": "brightness(0) invert(94%)",
                                "rm-action-hover": "brightness(0) saturate(100%) invert(14%) sepia(83%) saturate(2200%) hue-rotate(330deg) brightness(150%) contrast(124%)",
                                "rm-action-active": "brightness(0) saturate(100%) invert(14%) sepia(83%) saturate(2200%) hue-rotate(330deg) brightness(200%) contrast(124%)",

                                "mv-defult": "brightness(0) invert(94%)",
                                "mv-filter": "invert(62%) sepia(92%) saturate(1934%) hue-rotate(171deg) brightness(99%) contrast(84%)",

                                "act-defult": "brightness(0) invert(94%)",
                                "act-active": "invert(44%) sepia(89%) saturate(375%) hue-rotate(92deg) brightness(94%) contrast(91%)",
                                "act-active": "invert(60%) sepia(70%) saturate(358%) hue-rotate(97deg) brightness(94%) contrast(88%)",
                            },
                            master: {
                                "bg-color": "#0e0f10",
                                "fg-color": "#f0f0f0",
                                "topper-color": "#111214",
                                "hard-outline-color": "#444",
                                "tab-inactive": "#181a1d",
                                "dark-blue-hl": "#004e7a",
                                "lighter-blue-hl": "#00baff",
                                "blue-outline": "#0070a0",
                                "tab-inactive-blue": "#0c3c50",

                                "tab-close-1": "brightness(0) saturate(100%) invert(70%) hue-rotate(210deg)",
                                "tab-close-2": "brightness(1) saturate(75%) hue-rotate(340deg) brightness(100%)",
                                "tab-close-3": "brightness(1) saturate(100%) hue-rotate(340deg) brightness(100%)",

                                "action-btn-1": "brightness(1000) saturate(40%) hue-rotate(200deg) brightness(60%)",
                                "action-btn-2": "brightness(1000) saturate(40%) hue-rotate(200deg) brightness(90%)",
                                "action-btn-3": "brightness(1000) saturate(40%) hue-rotate(200deg) brightness(120%)",
                            }
                        }
