window.theme_temp =
`{
    indx: {
        "bg-color": "" <color>,
        "fg-color": "" <color>,

        "input-bg-color": "" <color>,
        "input-fg-color": "" <color>,
    },
    chungus: {
        "bg-color": "" <color>,
        "fg-color": "" <color>,
        "hard-outline-color": "" <color>,
        "dark-blue-hl": "" <color>,
        "light-blue-hl": "" <color>,
        "transparent-blue": "" <color>,
        "blue-outline": "" <color>,

        "icon-filter": "" <filter>,
        "icon-hover": "" <filter>,
        "icon-active": "" <filter>,

        "action-btn-1": "" <filter>,
        "action-btn-2": "" <filter>,
        "action-btn-3": "" <filter>,

        "action-btn-active-1": "" <filter>,
        "action-btn-active-2": "" <filter>,
        "action-btn-active-3": "" <filter>,

        "grey-40": "" <color>,
        "grey-50": "" <color>,
        "grey-80": "" <color>,
        "grey-90": "" <color>,
        "grey-99": "" <color>,
        "grey-ff": "" <color>,

        "grey-solid": "" <color>,
        "link-blue": "" <color>,
        "link-purple": "" <color>,
        "link-active-red": "" <color>,
        "bg-blue-dark": "" <color>,

        "code-bg": "" <color>,

        "copy-border": "" <color>,
        "copy-bg": "" <color>,
        "copy-fg": "" <color>,
        "copy-border-hover": "" <color>,
        "copy-bg-hover": "" <color>,
        "copy-border-active": "" <color>,
        "copy-bg-active": "" <color>,
        "copy-success-bd": "" <color>,
        "copy-success-bg": "" <color>,
        "copy-success-fg": "" <color>,

        "context-hover-border": "" <color>,
        "context-hover-bg": "" <color>,
        "context-hover-fg": "" <color>,
        "context-active-bg": "" <color>,

        "table-container-bg": "" <color>,
        "table-header-bg": "" <color>,
        "table-row-odd-bg": "" <color>,
        "table-row-even-bg": "" <color>,
        "table-header-fg": "" <color>,
    },
    prism: {
        "prism-block-bg": "" <color>,
        "prism-inline-bg": "" <color>,
        "prism-text-color": "" <color>,
        "prism-comment": "" <color>,
        "prism-block-comment": "" <color>,
        "prism-prolog": "" <color>,
        "prism-doctype": "" <color>,
        "prism-cdata": "" <color>,
        "prism-punctuation": "" <color>,
        "prism-tag": "" <color>,
        "prism-attr-name": "" <color>,
        "prism-attr-value": "" <color>,
        "prism-operator": "" <color>,
        "prism-entity": "" <color>,
        "prism-url": "" <color>,
        "prism-property": "" <color>,
        "prism-symbol": "" <color>,
        "prism-string": "" <color>,
        "prism-char": "" <color>,
        "prism-regex": "" <color>,
        "prism-number": "" <color>,
        "prism-constant": "" <color>,
        "prism-variable": "" <color>,
        "prism-class-name": "" <color>,
        "prism-function": "" <color>,
        "prism-function-name": "" <color>,
        "prism-keyword": "" <color>,
        "prism-selector": "" <color>,
        "prism-builtin": "" <color>,
        "prism-important": "" <color>,
        "prism-atrule": "" <color>,
        "prism-deleted": "" <color>,
        "prism-inserted": "" <color>,

        "prism-number-font-weight": "" <number>,
        "prism-keyword-font-weight": "" <number>,
        "prism-selector-font-weight": "" <number>,
        "prism-builtin-font-weight": "" <number>,
        "prism-important-font-weight": "" <number>,
        "prism-atrule-font-weight": "" <number>,
        "prism-bold-font-weight": "" <number>,
        "prism-italic-font-weight": "" <number>,
        "prism-property-font-weight": "" <number>,
        "prism-inserted-font-weight": "" <number>,
        "prism-function-name-font-weight": "" <number>,
        "prism-function-font-weight": "" <number>,
        "prism-class-name-font-weight": "" <number>,
        "prism-variable-font-weight": "" <number>,
        "prism-constant-font-weight": "" <number>,
        "prism-string-font-weight": "" <number>,
        "prism-regex-font-weight": "" <number>,
        "prism-char-font-weight": "" <number>,
        "prism-symbol-font-weight": "" <number>,
        "prism-url-font-weight": "" <number>,
        "prism-operator-font-weight": "" <number>,
        "prism-entity-font-weight": "" <number>,
        "prism-deleted-font-weight": "" <number>,
        "prism-attr-value-font-weight": "" <number>,
        "prism-attr-name-font-weight": "" <number>,
        "prism-tag-font-weight": "" <number>,
        "prism-punctuation-font-weight": "" <number>,
        "prism-cdata-font-weight": "" <number>,
        "prism-doctype-font-weight": "" <number>,
        "prism-prolog-font-weight": "" <number>,
        "prism-block-comment-font-weight": "" <number>,
        "prism-comment-font-weight": "" <number>,

        "prism-comment-font-style": "" <font-style>,
        "prism-block-comment-font-style": "" <font-style>,
        "prism-prolog-font-style": "" <font-style>,
        "prism-doctype-font-style": "" <font-style>,
        "prism-cdata-font-style": "" <font-style>,
        "prism-punctuation-font-style": "" <font-style>,
        "prism-tag-font-style": "" <font-style>,
        "prism-attr-name-font-style": "" <font-style>,
        "prism-attr-value-font-style": "" <font-style>,
        "prism-deleted-font-style": "" <font-style>,
        "prism-entity-font-style": "" <font-style>,
        "prism-operator-font-style": "" <font-style>,
        "prism-url-font-style": "" <font-style>,
        "prism-symbol-font-style": "" <font-style>,
        "prism-char-font-style": "" <font-style>,
        "prism-regex-font-style": "" <font-style>,
        "prism-string-font-style": "" <font-style>,
        "prism-number-font-style": "" <font-style>,
        "prism-constant-font-style": "" <font-style>,
        "prism-variable-font-style": "" <font-style>,
        "prism-class-name-font-style": "" <font-style>,
        "prism-function-font-style": "" <font-style>,
        "prism-function-name-font-style": "" <font-style>,
        "prism-keyword-font-style": "" <font-style>,
        "prism-selector-font-style": "" <font-style>,
        "prism-builtin-font-style": "" <font-style>,
        "prism-important-font-style": "" <font-style>,
        "prism-atrule-font-style": "" <font-style>,
        "prism-inserted-font-style": "" <font-style>,
        "prism-bold-font-style": "" <font-style>,
        "prism-italic-font-style": "" <font-style>,
        "prism-property-font-style": "" <font-style>,
    },
    gitgraph: {
        "versioning-graph-bg": "" <color>,
        "versioning-graph-right-border": "" <color>,

        "versioning-graph-0": "" <color>,
        "versioning-graph-1": "" <color>,
        "versioning-graph-2": "" <color>,
        "versioning-graph-3": "" <color>,
        "versioning-graph-4": "" <color>,
        "versioning-graph-5": "" <color>,
        "versioning-graph-6": "" <color>,
        "versioning-graph-7": "" <color>,
        "versioning-graph-8": "" <color>,
        "versioning-graph-9": "" <color>,
        "versioning-graph-a": "" <color>,
        "versioning-graph-b": "" <color>,
    },
    settings: {
        "bg-color": "" <color>,
        "fg-color": "" <color>,
        "menu-hover": "" <color>,
    },
    appearance: {
        "fg-color": "" <color>,
        "man-color": "" <color>,

        "card-1-filt": "" <filter>,
        "card-2-filt": "" <filter>,
        "card-3-filt": "" <filter>,

        "light-blue-hl": "" <color>,
    },
    morethemes: {
        "bg-color": "" <color>,
        "fg-color": "" <color>,
        "man-color": "" <color>,

        "card-1": "" <filter>,
        "card-2": "" <filter>,
        "card-3": "" <filter>,

        "icon-1": "" <filter>,
        "icon-2": "" <filter>,
        "icon-3": "" <filter>,
    },
    customthemes: {
        "bg-color": "" <color>,
        "fg-color": "" <color>,

        "icon-1": "" <filter>,
        "icon-2": "" <filter>,
        "icon-3": "" <filter>,
    },
    morefonts: {
        "bg-color": "" <color>,
        "fg-color": "" <color>,

        "hl-blue-1": "" <color>,
        "hl-blue-2": "" <color>,
        "hl-blue-3": "" <color>,
        "hl-blue-4": "" <color>,

        "icon-1": "" <filter>,
        "icon-2": "" <filter>,
        "icon-3": "" <filter>,
    },
    models: {
        "bg-color": "" <color>,
        "fg-color": "" <color>,
        "table-waght": "" <color>,

        "hl-blue-1": "" <color>,
        "hl-blue-2": "" <color>,

        "row-filter": "" <filter>,
        "filt-hover": "" <color>,
        "filt-raw": "" <color>,

        "rm-action-defult": "" <filter>,
        "rm-action-hover": "" <filter>,
        "rm-action-active": "" <filter>,

        "mv-defult": "" <filter>,
        "mv-filter": "" <filter>,

        "act-defult": "" <filter>,
        "act-active": "" <filter>,
        "act-active": "" <filter>,
    },
    master: {
        "bg-color": "" <color>,
        "fg-color": "" <color>,
        "topper-color": "" <color>,
        "hard-outline-color": "" <color>,
        "tab-inactive": "" <color>,
        "dark-blue-hl": "" <color>,
        "lighter-blue-hl": "" <color>,
        "blue-outline": "" <color>,
        "tab-inactive-blue": "" <color>,

        "tab-close-1": "" <filter>,
        "tab-close-2": "" <filter>,
        "tab-close-3": "" <filter>,

        "action-btn-1": "" <filter>,
        "action-btn-2": "" <filter>,
        "action-btn-3": "" <filter>,
    }
}`;
